name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v0.1.0)'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always
  GITHUB_REPO: zachhandley/FakeNotify

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            artifact: x86_64-gnu
            use_cross: false
          - target: x86_64-unknown-linux-musl
            artifact: x86_64-musl
            use_cross: true
          - target: aarch64-unknown-linux-gnu
            artifact: aarch64-gnu
            use_cross: true
          - target: aarch64-unknown-linux-musl
            artifact: aarch64-musl
            use_cross: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/setup-rust@main

      - name: Install cross
        if: matrix.use_cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Restore cache
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: restore
          key: cargo-fakenotify-release-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          path: ${{ env.CARGO_HOME }}/registry ${{ env.CARGO_HOME }}/git target
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

      - name: Build
        run: |
          if [ "${{ matrix.use_cross }}" = "true" ]; then
            cross build --release --target ${{ matrix.target }}
          else
            cargo build --release --target ${{ matrix.target }}
          fi

      - name: Package
        run: |
          mkdir -p dist
          cp $CARGO_TARGET_DIR/${{ matrix.target }}/release/fakenotifyd dist/fakenotifyd-${{ matrix.target }}
          cp $CARGO_TARGET_DIR/${{ matrix.target }}/release/libfakenotify_preload.so dist/libfakenotify_preload-${{ matrix.target }}.so

      - name: Upload artifacts
        uses: https://github.com/christopherhx/gitea-upload-artifact@v4
        with:
          name: binaries-${{ matrix.artifact }}
          path: dist/
          retention-days: 1

      - name: Save cache
        if: always()
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: save
          key: cargo-fakenotify-release-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          path: ${{ env.CARGO_HOME }}/registry ${{ env.CARGO_HOME }}/git target
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

  release-github:
    name: Release to GitHub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: https://github.com/christopherhx/gitea-download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release files
        run: |
          mkdir -p release

          # Copy all binaries
          find artifacts -type f -exec cp {} release/ \;

          # Create convenience copies (x86_64 musl = most portable)
          cp release/fakenotifyd-x86_64-unknown-linux-musl release/fakenotifyd
          cp release/libfakenotify_preload-x86_64-unknown-linux-musl.so release/libfakenotify_preload.so

          ls -la release/

      - name: Extract version
        id: version
        run: |
          if [ -n "${{ inputs.version }}" ]; then
            VERSION="${{ inputs.version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Push source to GitHub (excluding .forgejo)
        run: |
          # Configure git
          git config user.name "Forgejo CI"
          git config user.email "ci@forge.blackleafdigital.com"

          # Add GitHub as a remote
          git remote add github https://x-access-token:${{ secrets.GH_ACCESS_TOKEN }}@github.com/${{ env.GITHUB_REPO }}.git || true

          # Create a temporary branch without .forgejo
          git checkout -b github-release-${{ steps.version.outputs.version }}

          # Remove .forgejo from git tracking (but not from disk)
          git rm -r --cached .forgejo/ 2>/dev/null || true

          # Add .forgejo to .gitignore for this commit
          echo ".forgejo/" >> .gitignore
          git add .gitignore
          git commit -m "Exclude .forgejo from GitHub" --allow-empty

          # Force push to GitHub main
          git push github github-release-${{ steps.version.outputs.version }}:main --force

          # Also push the tag
          git tag -f ${{ steps.version.outputs.version }}
          git push github ${{ steps.version.outputs.version }} --force

      - name: Create GitHub Release
        run: |
          VERSION="${{ steps.version.outputs.version }}"

          # Create release via GitHub API
          RELEASE_RESPONSE=$(curl -s -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ env.GITHUB_REPO }}/releases" \
            -d "{\"tag_name\":\"$VERSION\",\"name\":\"FakeNotify $VERSION\",\"generate_release_notes\":true}")

          RELEASE_ID=$(echo "$RELEASE_RESPONSE" | jq -r '.id')
          echo "Release ID: $RELEASE_ID"

          if [ "$RELEASE_ID" = "null" ]; then
            echo "Failed to create release:"
            echo "$RELEASE_RESPONSE"
            exit 1
          fi

          # Upload each artifact
          for file in release/*; do
            filename=$(basename "$file")
            echo "Uploading $filename..."

            curl -s -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GH_ACCESS_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -H "Content-Type: application/octet-stream" \
              "https://uploads.github.com/repos/${{ env.GITHUB_REPO }}/releases/$RELEASE_ID/assets?name=$filename" \
              --data-binary "@$file"
          done

          echo "Release created: https://github.com/${{ env.GITHUB_REPO }}/releases/tag/$VERSION"

  docker:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download x86_64 musl artifacts
        uses: https://github.com/christopherhx/gitea-download-artifact@v4
        with:
          name: binaries-x86_64-musl
          path: dist

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: zachhandley
          password: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Extract version
        id: version
        run: |
          if [ -n "${{ inputs.version }}" ]; then
            VERSION="${{ inputs.version }}"
            VERSION="${VERSION#v}"
          else
            VERSION="${GITHUB_REF#refs/tags/v}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push daemon
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.release
          push: true
          tags: |
            ghcr.io/zachhandley/fakenotify:${{ steps.version.outputs.version }}
            ghcr.io/zachhandley/fakenotify:latest

      - name: Build and push DockerMod
        uses: docker/build-push-action@v6
        with:
          context: ./docker-mods
          push: true
          tags: |
            ghcr.io/zachhandley/fakenotify-mod:${{ steps.version.outputs.version }}
            ghcr.io/zachhandley/fakenotify-mod:latest
