name: Sync to GitHub

on:
  workflow_dispatch:

env:
  GITHUB_REPO: zachhandley/FakeNotify

jobs:
  sync:
    name: Sync to GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitHub (excluding .forgejo)
        run: |
          # Configure git
          git config user.name "Forgejo CI"
          git config user.email "ci@forge.blackleafdigital.com"

          # Add GitHub as a remote
          git remote add github https://x-access-token:${{ secrets.GH_ACCESS_TOKEN }}@github.com/${{ env.GITHUB_REPO }}.git || true

          # Create a temporary branch without .forgejo
          SYNC_BRANCH="sync-$(date +%s)"
          git checkout -b "$SYNC_BRANCH"

          # Remove .forgejo from git tracking (but not from disk)
          git rm -r --cached .forgejo/ 2>/dev/null || true

          # Add .forgejo to .gitignore for this commit
          echo ".forgejo/" >> .gitignore
          git add .gitignore
          git commit -m "Exclude .forgejo from GitHub" --allow-empty

          # Force push to GitHub main
          git push github "$SYNC_BRANCH":main --force

          echo "Synced to https://github.com/${{ env.GITHUB_REPO }}"
